export const TABLE_NAME = {
  USERS: "Users",
  IMAGES: "Images",
  FACES: "Faces",
  ALBUMS: "Albums",
};

export const S3_OBJECT_UPLOAD_STATUS = {
  PRESIGNED_URL_GENERATED: "PRESIGNED_URL_GENERATED",
  FAILED_TO_GENERATE_PRESIGNED_URL: "FAILED_TO_GENERATE_PRESIGNED_URL",
};

export const PRESIGNED_URL_EXPIRES_IN = {
  AN_HOUR: 60 * 60,
  HALF_AN_HOUR: 60 * 30,
  FIFTEEN_MINUTES: 60 * 15,
};
